# Generated by Django 4.0.5 on 2022-06-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_name_drink_drink_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='menu',
            field=models.ManyToManyField(to='product.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='drink',
            name='category',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='drink',
            name='drink_name',
            field=models.CharField(max_length=256),
        ),
    ]
